snapshot: Ignore ENOSYS (Function not implemented, errno 38) on readahead() failure (#3825)
I have a Stratum 1 with an obscure setup, it's a SmartOS/illumos LX branded zone running Rocky 9, thus it's an emulated kernel and the underlying filesystem is native ZFS. This  Linux kernel emulation does not implement the readahead() syscall

 The following error occurs reading the reflog on any attempt to snapshot:

```sh-session
[sandbox@cvmfs1-psu0 ~]$ CVMFS_SERVER_DEBUG=3 cvmfs_server snapshot sandbox.galaxyproject.org
...much output...
(download) Verify downloaded url http://localhost/cvmfs/sandbox.galaxyproject.org/.cvmfsreflog, proxy DIRECT (curl error 0)    [05-02-2025 20:20:13 UTC]
(sql) opening database file /var/spool/cvmfs/sandbox.galaxyproject.org/tmp/.cvmfsreflog.EzgRqh    [05-02-2025 20:20:13 UTC]
(sql) failed to read-ahead /var/spool/cvmfs/sandbox.galaxyproject.org/tmp/.cvmfsreflog.EzgRqh: invalid file descrp. or not open for reading (38)    [05-02-2025 20:20:13 UTC]
(sql) failed to open database file '/var/spool/cvmfs/sandbox.galaxyproject.org/tmp/.cvmfsreflog.EzgRqh'    [05-02-2025 20:20:13 UTC]
(sql) closing SQLite database '/var/spool/cvmfs/sandbox.galaxyproject.org/tmp/.cvmfsreflog.EzgRqh' (unlink: no)    [05-02-2025 20:20:13 UTC]
failed loading reflog (2 - local I/O failure)
cvmfs_swissknife_debug: /host/cvmfs/cvmfs/swissknife_pull.cc:714: virtual int swissknife::CommandPull::Main(const ArgumentList&): Assertion `reflog != NULL' failed.
/bin/cvmfs_server: line 7528: 209459 Aborted                 (core dumped) $user_shell "$(__swissknife_cmd dbg) pull -m $name         -u $stratum0                                           -w $stratum1                                           -r ${upstream}                                         -x ${spool_dir}/tmp                                    -k $public_key                                         -n $num_workers                                        -t $timeout                                            -a $retries $with_history $with_reflog                    $initial_snapshot_flag $timestamp_threshold $log_level"
```

This appeared in 2.11.0, the breaking change was #3305. This fixes this error by ignoring ENOSYS.

Co-authored-by: Valentin Volkl <valentin.volkl@cern.ch>